---
title: "Italian Analysis"
author: "Dr. Paul Gronke"
date: "`r Sys.Date()`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
library(stringi)

```

## My Italian Analysis

This is my analysis of the Effective Number of Parties in Italy from 1990 to 2025. 


```{r readdata, echo = FALSE, include = TRUE}
# Load the data 
# Loads clea_lc_20240419

load(url("https://www.dropbox.com/scl/fi/kp1lty1chtgzye8gnufl4/clea_lc_20240419.RData?rlkey=phvtoh91a48v9jky1m1120vnw&st=h7lnys7v&dl=1"))

italy_data <- clea_lc_20240419 %>%
  filter(ctr_n == "Italy" & yr >= 2000 & yr <= 2025) 
# For some reason, all the seat totals prior to 2000 are -990 


italy_2013 <- italy_data %>%
  filter(ctr_n == "Italy", yr == 2013)

italy_2013_enp <- italy_2013 %>%
  group_by(yr, cst) %>%
  summarize(enp_v = 1/sum(pvs1^2),
            enp_s = 1/sum((seat/mag)^2))

italy_enp <- italy_data %>%
  group_by(yr, cst) %>%
  summarize(enp_v = 1/sum(pvs1^2),
            enp_s = 1/sum((seat/mag)^2))

## 2) Standardize the party identifier to a single key
##    - use the LABEL if present, else the raw value
##    - trim spaces; normalize accents; keep a consistent case
mk_party_key <- function(x) {
  x_chr <- as.character(haven::as_factor(x))    # turns labelled/factor -> labels
  x_chr <- stri_trim_both(x_chr)
  x_chr <- stri_trans_nfkc(x_chr)               # normalize diacritics/width
  x_chr
}

## 3) Collapse to one row per (yr, party)
italy_national_partydata <- italy_data %>%
  mutate(pty_key = mk_party_key(pty)) %>%
  group_by(yr, pty_key, .drop = TRUE) %>%
  summarize(
    pty_v = sum(pv1,  na.rm = TRUE),            # total votes per party
    pty_s = sum(seat, na.rm = TRUE),            # total seats per party
    .groups = "drop"
  )

## 4) (Optional) quick check for any lingering dupes (should be none)
italy_national_partydata %>%
  count(yr, pty_key) %>%
  filter(n > 1)

## 5) Turn those totals into national ENP for that year
italy_enp_national <- italy_national_partydata %>%
  group_by(yr) %>%
  mutate(
    vote_share = pty_v / sum(pty_v, na.rm = TRUE),
    seat_share = pty_s / sum(pty_s, na.rm = TRUE)
  ) %>%
  summarize(
    ENP_votes = 1 / sum(vote_share^2, na.rm = TRUE),
    ENP_seats = 1 / sum(seat_share^2, na.rm = TRUE),
    .groups = "drop"
  )

```
